# Generated by Django 2.0.5 on 2018-05-26 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_text', models.CharField(max_length=16)),
                ('inspect_text', models.TextField()),
                ('inspected', models.BooleanField(default=False)),
                ('attempted', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('lock_text', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Door',
                'verbose_name_plural': 'Doors',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventory',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('clean_name', models.CharField(default='', max_length=64)),
                ('inspect_text', models.TextField()),
                ('obtainable', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('text', models.TextField()),
                ('slack_channel', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slack_channel', models.CharField(max_length=16)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ptmo.Level')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('clean_name', models.CharField(blank=True, max_length=64, null=True)),
                ('text', models.TextField()),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ptmo.Location')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='RoomItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_text', models.CharField(blank=True, max_length=16, null=True)),
                ('inspected', models.BooleanField(default=False)),
                ('attempted', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('lock_text', models.CharField(blank=True, max_length=64, null=True)),
                ('force_text', models.CharField(blank=True, max_length=64, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ptmo.Item')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ptmo.Room')),
            ],
            options={
                'verbose_name': 'RoomItem',
                'verbose_name_plural': 'RoomItems',
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ptmo.Item'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='door',
            name='curr_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_room', to='ptmo.Room'),
        ),
        migrations.AddField(
            model_name='door',
            name='dest_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='destination_room', to='ptmo.Room'),
        ),
    ]
