# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('text', models.CharField(max_length=16)),
                ('locked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Door',
                'verbose_name_plural': 'Doors',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('text', models.CharField(max_length=16)),
                ('locked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Door',
                'verbose_name_plural': 'Doors',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slack_channel', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('text', models.CharField(max_length=255)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptmo.Location')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='curr_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptmo.Room'),
        ),
        migrations.AddField(
            model_name='door',
            name='curr_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_room', to='ptmo.Room'),
        ),
        migrations.AddField(
            model_name='door',
            name='dest_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_room', to='ptmo.Room'),
        ),
    ]
