# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptmo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.RemoveField(
            model_name='door',
            name='name',
        ),
        migrations.AddField(
            model_name='room',
            name='clean_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
