# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptmo', '0004_auto_20170526_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='button_text',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
