# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptmo', '0005_auto_20170526_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='attempted',
        ),
        migrations.RemoveField(
            model_name='item',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='item',
            name='inspected',
        ),
        migrations.RemoveField(
            model_name='item',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='item',
            name='room',
        ),
        migrations.AddField(
            model_name='roomitem',
            name='attempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomitem',
            name='button_text',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='roomitem',
            name='inspected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomitem',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
