# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptmo', '0006_auto_20170526_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='obtainable',
            field=models.BooleanField(default=False),
        ),
    ]
