# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptmo', '0007_item_obtainable'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='lock_text',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='roomitem',
            name='lock_text',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
