# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptmo', '0008_auto_20170526_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='lock_text',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='roomitem',
            name='lock_text',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
