# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptmo', '0009_auto_20170526_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='inspected',
            field=models.BooleanField(default=False),
        ),
    ]
