# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptmo', '0010_door_inspected'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomitem',
            name='force_text',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
