# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptmo', '0012_auto_20170527_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='clean_name',
            field=models.CharField(default=b'', max_length=64),
        ),
    ]
