# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptmo', '0013_item_clean_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
