# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('age', models.IntegerField()),
                ('CHA', models.IntegerField()),
                ('CON', models.IntegerField()),
                ('DEX', models.IntegerField()),
                ('INT', models.IntegerField()),
                ('STR', models.IntegerField()),
                ('WIL', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('height', models.CharField(max_length=16)),
                ('CHA', models.IntegerField()),
                ('CON', models.IntegerField()),
                ('DEX', models.IntegerField()),
                ('INT', models.IntegerField()),
                ('STR', models.IntegerField()),
                ('WIL', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Race',
                'verbose_name_plural': 'Races',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfarog.Race'),
        ),
    ]
