# Generated by Django 2.0.5 on 2018-07-04 14:52

from django.conf import settings
from django.db import migrations, models
from django.core.management import call_command
import django.db.models.deletion
import source_framework.core.utils.model

def load_fixture(apps, schema_editor):
    call_command('loaddata', fixture, app_label='myfarog')

def unload_fixture(apps, schema_editor):
    pass


fixture = 'init3.json'

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Battle',
                'verbose_name_plural': 'Battles',
            },
            bases=(models.Model, source_framework.core.utils.model.SourceModelMixin),
        ),
        migrations.CreateModel(
            name='BattleRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=1)),
                ('step', models.IntegerField(default=0)),
                ('pending_actions', models.IntegerField(default=0)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rounds', to='myfarog.Battle')),
            ],
            options={
                'verbose_name': 'Battle Round',
                'verbose_name_plural': 'Battle Rounds',
            },
        ),
        migrations.CreateModel(
            name='BattleRoundAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('parameters', models.CharField(default=None, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Battle Round Action',
                'verbose_name_plural': 'Battle Round Actions',
            },
            bases=(models.Model, source_framework.core.utils.model.SourceModelMixin),
        ),
        migrations.CreateModel(
            name='BattleRoundInitiative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('battle_round', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='initiatives', to='myfarog.BattleRound')),
            ],
            options={
                'verbose_name': 'Battle Round Initiative',
                'verbose_name_plural': 'Battle Round Initiatives',
            },
            bases=(models.Model, source_framework.core.utils.model.SourceModelMixin),
        ),
        migrations.CreateModel(
            name='BattleRoundLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('attack', 'Attack'), ('cast', 'Cast'), ('use', 'Use')], max_length=100)),
                ('statement', models.CharField(max_length=500)),
                ('results', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Battle Round Log',
                'verbose_name_plural': 'Battle Round Logs',
            },
            bases=(models.Model, source_framework.core.utils.model.SourceModelMixin),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=16)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=16)),
                ('age', models.IntegerField(default=0)),
                ('handedness', models.CharField(choices=[('right', 'Right'), ('left', 'Left')], default='right', max_length=10)),
                ('CHA', models.IntegerField(default=0)),
                ('CON', models.IntegerField(default=0)),
                ('DEX', models.IntegerField(default=0)),
                ('INT', models.IntegerField(default=0)),
                ('STR', models.IntegerField(default=0)),
                ('WIL', models.IntegerField(default=0)),
                ('_cha', models.IntegerField(default=0)),
                ('_con', models.IntegerField(default=0)),
                ('_dex', models.IntegerField(default=0)),
                ('_int', models.IntegerField(default=0)),
                ('_str', models.IntegerField(default=0)),
                ('_wil', models.IntegerField(default=0)),
                ('HP', models.IntegerField(default=0)),
                ('SP', models.IntegerField(default=0)),
                ('MHP', models.IntegerField(default=0)),
                ('max_HP', models.IntegerField(default=0)),
                ('max_SP', models.IntegerField(default=0)),
                ('max_MHP', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('OV_melee', models.IntegerField(default=0)),
                ('OV_missile', models.IntegerField(default=0)),
                ('DV_melee', models.IntegerField(default=0)),
                ('DV_missile', models.IntegerField(default=0)),
                ('encumbrance_status', models.CharField(choices=[('Light', 'Light'), ('Medium', 'Medium'), ('Heavy', 'Heavy')], default='Light', max_length=16)),
                ('encumbrance_mod', models.IntegerField(default=0)),
                ('health_status', models.CharField(choices=[('Normal', 'Normal'), ('Seriously Injured', 'Seriously Injured'), ('Severely Injured', 'Severely Injured'), ('Fatally Injured', 'Fatally Injured')], default='Normal', max_length=16)),
                ('health_mod', models.IntegerField(default=0)),
                ('mental_health_status', models.CharField(choices=[('Normal', 'Normal'), ('Stressed', 'Stressed'), ('Agitated', 'Agitated'), ('Deranged', 'Deranged'), ('Pyschotic', 'Pyschotic')], default='Normal', max_length=16)),
                ('mental_health_mod', models.IntegerField(default=0)),
                ('stamina_status', models.CharField(choices=[('Normal', 'Normal'), ('Tired', 'Tired'), ('Weary', 'Weary'), ('Exhausted', 'Exhausted'), ('Unconscious', 'Unconscious')], default='Normal', max_length=16)),
                ('stamina_mod', models.IntegerField(default=0)),
                ('stun_status', models.CharField(choices=[('Normal', 'Normal'), ('Stunned', 'Strunned'), ('Knocked Down', 'Knocked Down'), ('Knocked Out', 'Knocked Out')], default='Normal', max_length=16)),
                ('stun_rounds', models.IntegerField(default=0)),
                ('morale_status', models.CharField(choices=[('Normal', 'Normal'), ('Nervous', 'Nervous'), ('Afraid', 'Afraid'), ('Fearful', 'Fearful'), ('Terrified', 'Terrified'), ('Panic', 'Panic')], default='Normal', max_length=16)),
                ('morale_rounds', models.IntegerField(default=0)),
                ('morale_check_bonus', models.IntegerField(default=0)),
                ('morale_mod', models.IntegerField(default=0)),
                ('psychotic_count', models.IntegerField(default=0)),
                ('trauma_count', models.IntegerField(default=0)),
                ('fright_mod', models.IntegerField(default=0)),
                ('initiative_check_bonus', models.IntegerField(default=0)),
                ('current_battle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Battle')),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
            },
            bases=(models.Model, source_framework.core.utils.model.SourceModelMixin),
        ),
        migrations.CreateModel(
            name='CharacterCompartmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='myfarog.Character')),
            ],
            options={
                'verbose_name': 'Character Compartment Item',
                'verbose_name_plural': 'Character Compartment Item',
            },
            bases=(models.Model, source_framework.core.utils.model.SourceModelMixin),
        ),
        migrations.CreateModel(
            name='CharacterCut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('Light', 'Light'), ('Medium', 'Medium'), ('Serious', 'Serious')], max_length=10)),
                ('rounds_active', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cuts', to='myfarog.Character')),
            ],
            options={
                'verbose_name': 'Character Cut',
                'verbose_name_plural': 'Character Cuts',
            },
            bases=(models.Model, source_framework.core.utils.model.SourceModelMixin),
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trained', models.BooleanField(default=False)),
                ('role_skill', models.BooleanField(default=False)),
                ('mod', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='_skills', to='myfarog.Character')),
            ],
            options={
                'verbose_name': 'Character Skill',
                'verbose_name_plural': 'Character Skills',
            },
            bases=(models.Model, source_framework.core.utils.model.SourceModelMixin),
        ),
        migrations.CreateModel(
            name='CharacterTalent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='talents', to='myfarog.Character')),
            ],
            options={
                'verbose_name': 'Character Talent',
                'verbose_name_plural': 'Character Talent',
            },
            bases=(models.Model, source_framework.core.utils.model.SourceModelMixin),
        ),
        migrations.CreateModel(
            name='Compartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('main', 'Main'), ('pocket', 'pocket')], max_length=100)),
                ('hidden', models.BooleanField(default=False)),
                ('lockable', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Compartment',
                'verbose_name_plural': 'compartments',
            },
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Culture',
                'verbose_name_plural': 'Cultures',
            },
            bases=(models.Model, source_framework.core.utils.model.SourceModelMixin),
        ),
        migrations.CreateModel(
            name='CultureGenderSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=16)),
                ('culture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cultures', to='myfarog.Culture')),
            ],
            options={
                'verbose_name': 'Culture Skill',
                'verbose_name_plural': 'Culture Skills',
            },
            bases=(models.Model, source_framework.core.utils.model.SourceModelMixin),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('shirt', 'Shirt'), ('pants', 'Pants'), ('weapon', 'Weapon'), ('armor', 'Armor'), ('helmet', 'Helmet'), ('shield', 'Shield'), ('gloves', 'Gloves'), ('belt', 'Belt'), ('footwear', 'Footwear'), ('necklace', 'Necklace'), ('earring', 'Earring'), ('ring', 'Ring'), ('trinket', 'Trinket'), ('backpack', 'Backpack'), ('sack', 'Sack'), ('misc', 'Misc')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('weight', models.IntegerField()),
                ('unique', models.BooleanField(default=False)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='ItemBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Item Bonus',
                'verbose_name_plural': 'Item Bonuses',
            },
        ),
        migrations.CreateModel(
            name='ItemBonusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Item Bonus Type',
                'verbose_name_plural': 'Item Bonus Types',
            },
        ),
        migrations.CreateModel(
            name='ItemMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Item Material',
                'verbose_name_plural': 'Item Material',
            },
        ),
        migrations.CreateModel(
            name='ItemPrerequisites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CHA', 'CHA'), ('CON', 'CON'), ('DEX', 'DEX'), ('INT', 'INT'), ('STR', 'STR'), ('WIL', 'WIL'), ('Role', 'Role'), ('Life Stance', 'Life Stance'), ('Social Class', 'Social Class')], max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Item Prerequisites',
                'verbose_name_plural': 'Item Prerequisites',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('characters', models.ManyToManyField(blank=True, related_name='parties', related_query_name='parties', to='myfarog.Character')),
                ('frightener', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='party_frightener', to='myfarog.Character')),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
            },
            bases=(models.Model, source_framework.core.utils.model.SourceModelMixin),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='RoleSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Role')),
            ],
            options={
                'verbose_name': 'Role Skill',
                'verbose_name_plural': 'Role Skills',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('CS', 'Combat Skill'), ('MS', 'Movement Skill'), ('SS', 'Special Skill')], max_length=4)),
                ('attribute', models.CharField(choices=[('CHA', 'CHA'), ('CON', 'CON'), ('DEX', 'DEX'), ('INT', 'INT'), ('STR', 'STR'), ('WIL', 'WIL')], max_length=16)),
                ('untrained', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender_ratio', models.IntegerField(default=50, help_text='The value used here will be the cutoff value for a 1-100 scale, where the lower portion is Female, and the higher Male')),
                ('age', models.CharField(help_text='Dice Format', max_length=100)),
                ('maximum_age', models.IntegerField(default=5, help_text="This number will be multipled by the Character's CON")),
            ],
            options={
                'verbose_name': 'Species',
                'verbose_name_plural': 'Species',
            },
        ),
        migrations.CreateModel(
            name='SpeciesGenderMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=16)),
                ('height', models.CharField(max_length=16)),
                ('CHA', models.IntegerField()),
                ('CON', models.IntegerField()),
                ('DEX', models.IntegerField()),
                ('INT', models.IntegerField()),
                ('STR', models.IntegerField()),
                ('WIL', models.IntegerField()),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gender_mods', to='myfarog.Species')),
            ],
            options={
                'verbose_name': 'Species Gender Mod',
                'verbose_name_plural': 'Species Gender Mods',
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('power_level', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Spell',
                'verbose_name_plural': 'Spells',
            },
        ),
        migrations.CreateModel(
            name='SpellElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Spell Element',
                'verbose_name_plural': 'Spell Elements',
            },
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prerequisite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Talent')),
            ],
            options={
                'verbose_name': 'Talent',
                'verbose_name_plural': 'Talents',
            },
        ),
        migrations.CreateModel(
            name='TalentExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.CharField(choices=[('Cold Toughness', 'Cold Toughness'), ('Disease Resistance', 'Disease Resistance'), ('Electrical Toughness', 'Electrical Toughness'), ('Heat Toughness', 'Heat Toughness'), ('Initiative', 'Initiative'), ('Morale', 'Morale'), ('Mental Toughness', 'Mental Toughness'), ('Physical Toughness', 'Physical Toughness'), ('Posion Resistance', 'Posion Resistance')], max_length=50)),
                ('mod', models.IntegerField()),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Talent')),
            ],
            options={
                'verbose_name': 'Talent Extra',
                'verbose_name_plural': 'Talent Extras',
            },
        ),
        migrations.CreateModel(
            name='TalentSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod', models.IntegerField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Skill')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='skills', to='myfarog.Talent')),
            ],
            options={
                'verbose_name': 'Talent Skill',
                'verbose_name_plural': 'Talent Skills',
            },
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfarog.Item')),
                ('AV', models.IntegerField(default=0)),
                ('MS_mod', models.IntegerField(default=0)),
                ('stealth_mod', models.IntegerField(default=0)),
                ('swimming_mod', models.IntegerField(default=0)),
                ('damage', models.CharField(default=0, max_length=50)),
            ],
            options={
                'verbose_name': 'Armor',
                'verbose_name_plural': 'Armor',
            },
            bases=('myfarog.item',),
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfarog.Item')),
            ],
            options={
                'verbose_name': 'Container',
                'verbose_name_plural': 'Containers',
            },
            bases=('myfarog.item',),
        ),
        migrations.CreateModel(
            name='Earring',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfarog.Item')),
            ],
            options={
                'verbose_name': 'Earring',
                'verbose_name_plural': 'Earrings',
            },
            bases=('myfarog.item',),
        ),
        migrations.CreateModel(
            name='Footwear',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfarog.Item')),
            ],
            options={
                'verbose_name': 'Footwear',
                'verbose_name_plural': 'Footwear',
            },
            bases=('myfarog.item',),
        ),
        migrations.CreateModel(
            name='Glove',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfarog.Item')),
            ],
            options={
                'verbose_name': 'Glove',
                'verbose_name_plural': 'Gloves',
            },
            bases=('myfarog.item',),
        ),
        migrations.CreateModel(
            name='Helmet',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfarog.Item')),
                ('AV', models.IntegerField(default=0)),
                ('perception_mod', models.IntegerField(default=0)),
                ('missile_mod', models.IntegerField(default=0)),
                ('shading_mod', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Helmet',
                'verbose_name_plural': 'Helmets',
            },
            bases=('myfarog.item',),
        ),
        migrations.CreateModel(
            name='Necklace',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfarog.Item')),
            ],
            options={
                'verbose_name': 'Necklace',
                'verbose_name_plural': 'Necklaces',
            },
            bases=('myfarog.item',),
        ),
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfarog.Item')),
            ],
            options={
                'verbose_name': 'Ring',
                'verbose_name_plural': 'Rings',
            },
            bases=('myfarog.item',),
        ),
        migrations.CreateModel(
            name='Shield',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfarog.Item')),
                ('ME', models.IntegerField(default=0)),
                ('MI', models.IntegerField(default=0)),
                ('MS_mod', models.IntegerField(default=0)),
                ('damage', models.CharField(default=0, max_length=50)),
                ('cut', models.IntegerField(default=0)),
                ('shock', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Shield',
                'verbose_name_plural': 'Shields',
            },
            bases=('myfarog.item',),
        ),
        migrations.CreateModel(
            name='Trinket',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfarog.Item')),
            ],
            options={
                'verbose_name': 'Trinket',
                'verbose_name_plural': 'Trinkets',
            },
            bases=('myfarog.item',),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfarog.Item')),
                ('damage', models.CharField(default=0, max_length=50)),
                ('weapon_type', models.CharField(choices=[('melee', 'Melee'), ('missile', 'Missile'), ('small Weapon', 'Small_weapon'), ('heavy Weapon', 'Heavy_weapon')], max_length=50)),
                ('cut', models.IntegerField(default=0)),
                ('shock', models.IntegerField(default=0)),
                ('range', models.IntegerField(default=0)),
                ('OV_mod', models.IntegerField(default=0)),
                ('DV_mod', models.IntegerField(default=0)),
                ('AP', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Weapon',
                'verbose_name_plural': 'Weapons',
            },
            bases=('myfarog.item',),
        ),
        migrations.AddField(
            model_name='spell',
            name='elements',
            field=models.ManyToManyField(blank=True, related_name='spell', related_query_name='spell', to='myfarog.SpellElement'),
        ),
        migrations.AddField(
            model_name='roleskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Skill'),
        ),
        migrations.AddField(
            model_name='itembonus',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.ItemBonusType'),
        ),
        migrations.AddField(
            model_name='item',
            name='bonuses',
            field=models.ManyToManyField(blank=True, related_name='items', related_query_name='items', to='myfarog.ItemBonus'),
        ),
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.ItemMaterial'),
        ),
        migrations.AddField(
            model_name='item',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='items', related_query_name='items', to='myfarog.ItemPrerequisites'),
        ),
        migrations.AddField(
            model_name='culturegenderskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='skills', to='myfarog.Skill'),
        ),
        migrations.AddField(
            model_name='charactertalent',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Talent'),
        ),
        migrations.AddField(
            model_name='characterskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Skill'),
        ),
        migrations.AddField(
            model_name='charactercompartmentitem',
            name='compartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Compartment'),
        ),
        migrations.AddField(
            model_name='charactercompartmentitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Item'),
        ),
        migrations.AddField(
            model_name='character',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Role'),
        ),
        migrations.AddField(
            model_name='character',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Species'),
        ),
        migrations.AddField(
            model_name='character',
            name='spells',
            field=models.ManyToManyField(blank=True, related_name='spells', related_query_name='spells', to='myfarog.Spell'),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='battleroundlog',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='actor_logs', to='myfarog.Character'),
        ),
        migrations.AddField(
            model_name='battleroundlog',
            name='battle_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='myfarog.BattleRound'),
        ),
        migrations.AddField(
            model_name='battleroundlog',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='target_logs', to='myfarog.Character'),
        ),
        migrations.AddField(
            model_name='battleroundinitiative',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='round_initiatives', to='myfarog.Character'),
        ),
        migrations.AddField(
            model_name='battleroundaction',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='actor_actions', to='myfarog.Character'),
        ),
        migrations.AddField(
            model_name='battleroundaction',
            name='battle_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='actions', to='myfarog.BattleRound'),
        ),
        migrations.AddField(
            model_name='battleround',
            name='damaged_characters',
            field=models.ManyToManyField(blank=True, related_name='damaged_rounds', related_query_name='damaged_rounds', to='myfarog.Character'),
        ),
        migrations.AddField(
            model_name='battle',
            name='parties',
            field=models.ManyToManyField(blank=True, related_name='battles', related_query_name='battles', to='myfarog.Party'),
        ),
        migrations.CreateModel(
            name='Belt',
            fields=[
                ('container_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfarog.Container')),
            ],
            options={
                'verbose_name': 'Belt',
                'verbose_name_plural': 'Belts',
            },
            bases=('myfarog.container',),
        ),
        migrations.CreateModel(
            name='Jacket',
            fields=[
                ('container_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfarog.Container')),
            ],
            options={
                'verbose_name': 'Jacket',
                'verbose_name_plural': 'Jackets',
            },
            bases=('myfarog.container',),
        ),
        migrations.CreateModel(
            name='Pants',
            fields=[
                ('container_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfarog.Container')),
            ],
            options={
                'verbose_name': 'Pants',
                'verbose_name_plural': 'Pants',
            },
            bases=('myfarog.container',),
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('container_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfarog.Container')),
            ],
            options={
                'verbose_name': 'Shirt',
                'verbose_name_plural': 'Shirts',
            },
            bases=('myfarog.container',),
        ),
        migrations.AddField(
            model_name='compartment',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='compartments', to='myfarog.Container'),
        ),
        migrations.AddField(
            model_name='character',
            name='armor_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Armor'),
        ),
        migrations.AddField(
            model_name='character',
            name='footwear_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Footwear'),
        ),
        migrations.AddField(
            model_name='character',
            name='helmet_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Helmet'),
        ),
        migrations.AddField(
            model_name='character',
            name='left_earring_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='left_ear', to='myfarog.Earring'),
        ),
        migrations.AddField(
            model_name='character',
            name='left_glove_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='left_glove', to='myfarog.Glove'),
        ),
        migrations.AddField(
            model_name='character',
            name='left_hand_shield',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='left_hand', to='myfarog.Shield'),
        ),
        migrations.AddField(
            model_name='character',
            name='left_hand_weapon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='left_hand', to='myfarog.Weapon'),
        ),
        migrations.AddField(
            model_name='character',
            name='necklace_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Necklace'),
        ),
        migrations.AddField(
            model_name='character',
            name='right_earring_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='right_ear', to='myfarog.Earring'),
        ),
        migrations.AddField(
            model_name='character',
            name='right_glove_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='right_glove', to='myfarog.Glove'),
        ),
        migrations.AddField(
            model_name='character',
            name='right_hand_shield',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='right_hand', to='myfarog.Shield'),
        ),
        migrations.AddField(
            model_name='character',
            name='right_hand_weapon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='right_hand', to='myfarog.Weapon'),
        ),
        migrations.AddField(
            model_name='character',
            name='ring_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Ring'),
        ),
        migrations.AddField(
            model_name='character',
            name='trinket_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Trinket'),
        ),
        migrations.AddField(
            model_name='character',
            name='pants_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Pants'),
        ),
        migrations.AddField(
            model_name='character',
            name='shirt_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Shirt'),
        ),
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
