# Generated by Django 2.0.5 on 2018-06-02 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myfarog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=16)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=16)),
                ('age', models.IntegerField(default=0)),
                ('handedness', models.CharField(choices=[('right', 'Right'), ('left', 'Left')], default='right', max_length=10)),
                ('CHA', models.IntegerField(default=0)),
                ('CON', models.IntegerField(default=0)),
                ('DEX', models.IntegerField(default=0)),
                ('INT', models.IntegerField(default=0)),
                ('STR', models.IntegerField(default=0)),
                ('WIL', models.IntegerField(default=0)),
                ('_cha', models.IntegerField(default=0)),
                ('_con', models.IntegerField(default=0)),
                ('_dex', models.IntegerField(default=0)),
                ('_int', models.IntegerField(default=0)),
                ('_str', models.IntegerField(default=0)),
                ('_wil', models.IntegerField(default=0)),
                ('HP', models.IntegerField(default=0)),
                ('SP', models.IntegerField(default=0)),
                ('MHP', models.IntegerField(default=0)),
                ('max_HP', models.IntegerField(default=0)),
                ('max_SP', models.IntegerField(default=0)),
                ('max_MHP', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('OV_melee', models.IntegerField(default=0)),
                ('OV_missile', models.IntegerField(default=0)),
                ('DV_melee', models.IntegerField(default=0)),
                ('DV_missile', models.IntegerField(default=0)),
                ('encumbrance_status', models.CharField(choices=[('Light', 'Light'), ('Medium', 'Medium'), ('Heavy', 'Heavy')], default='Light', max_length=16)),
                ('encumbrance_mod', models.IntegerField(default=0)),
                ('health_status', models.CharField(choices=[('Normal', 'Normal'), ('Seriously Injured', 'Seriously Injured'), ('Severely Injured', 'Severely Injured'), ('Fatally Injured', 'Fatally Injured')], default='Normal', max_length=16)),
                ('health_mod', models.IntegerField(default=0)),
                ('mental_health_status', models.CharField(choices=[('Normal', 'Normal'), ('Stressed', 'Stressed'), ('Agitated', 'Agitated'), ('Deranged', 'Deranged'), ('Pyschotic', 'Pyschotic')], default='Normal', max_length=16)),
                ('mental_health_mod', models.IntegerField(default=0)),
                ('stamina_status', models.CharField(choices=[('Normal', 'Normal'), ('Tired', 'Tired'), ('Exhausted', 'Exhausted'), ('Unconscious', 'Unconscious')], default='Normal', max_length=16)),
                ('stamina_mod', models.IntegerField(default=0)),
                ('stun_status', models.CharField(choices=[('Normal', 'Normal'), ('Knocked Down', 'Knocked Down'), ('Knocked Out', 'Knocked Out')], default='Normal', max_length=16)),
                ('stun_rounds', models.IntegerField(default=0)),
                ('morale_status', models.CharField(choices=[('Normal', 'Normal'), ('Nervous', 'Nervous'), ('Afraid', 'Afraid'), ('Fearful', 'Fearful'), ('Terrified', 'Terrified'), ('Panic', 'Panic')], default='Normal', max_length=16)),
                ('morale_rounds', models.IntegerField(default=0)),
                ('morale_check_bonus', models.IntegerField(default=0)),
                ('pyschotic_count', models.IntegerField(default=0)),
                ('trauma_count', models.IntegerField(default=0)),
                ('fright_mod', models.IntegerField(default=0)),
                ('initiative_check_bonus', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
            },
            managers=[
                ('objects', myfarog.models.CharacterManager()),
            ],
        ),
        migrations.CreateModel(
            name='CharacterCut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('Light', 'Light'), ('Medium', 'Medium'), ('Serious', 'Serious')], max_length=10)),
                ('rounds_active', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Character')),
            ],
            options={
                'verbose_name': 'Character Cut',
                'verbose_name_plural': 'Character Cuts',
            },
        ),
        migrations.CreateModel(
            name='CharacterInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipped', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory', to='myfarog.Character')),
            ],
            options={
                'verbose_name': 'Character Inventory',
                'verbose_name_plural': 'Character Inventory',
            },
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trained', models.BooleanField(default=False)),
                ('role_skill', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Character')),
            ],
            options={
                'verbose_name': 'Character Skill',
                'verbose_name_plural': 'Character Skills',
            },
        ),
        migrations.CreateModel(
            name='CharacterTalent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Character')),
            ],
            options={
                'verbose_name': 'Character Talent',
                'verbose_name_plural': 'Character Talent',
            },
        ),
        migrations.CreateModel(
            name='InventorySlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Shirt', 'Shirt'), ('Pants', 'Pants'), ('Weapon', 'Weapon'), ('Armor', 'Armor'), ('Helmet', 'Helmet'), ('Shield', 'Shield'), ('Gloves', 'Gloves'), ('Footwear', 'Footwear'), ('Necklace', 'Necklace'), ('Earring', 'Earring'), ('Ring', 'Ring'), ('Trinket', 'Trinket'), ('Misc', 'Misc')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('weight', models.IntegerField()),
                ('unique', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='ItemBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Item Bonus',
                'verbose_name_plural': 'Item Bonuses',
            },
        ),
        migrations.CreateModel(
            name='ItemBonusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Item Bonus Type',
                'verbose_name_plural': 'Item Bonus Types',
            },
        ),
        migrations.CreateModel(
            name='ItemMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Item Material',
                'verbose_name_plural': 'Item Material',
            },
        ),
        migrations.CreateModel(
            name='ItemPrerequisites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CHA', 'CHA'), ('CON', 'CON'), ('DEX', 'DEX'), ('INT', 'INT'), ('STR', 'STR'), ('WIL', 'WIL'), ('Role', 'Role'), ('Life Stance', 'Life Stance'), ('Social Class', 'Social Class')], max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Item Prerequisites',
                'verbose_name_plural': 'Item Prerequisites',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='RolePrerequisites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CHA', 'CHA'), ('CON', 'CON'), ('DEX', 'DEX'), ('INT', 'INT'), ('STR', 'STR'), ('WIL', 'WIL'), ('Talent', 'Talent'), ('Life Stance', 'Life Stance'), ('Social Class', 'Social Class')], max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Role Prerequisites',
                'verbose_name_plural': 'Role Prerequisites',
            },
        ),
        migrations.CreateModel(
            name='RoleSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Role')),
            ],
            options={
                'verbose_name': 'Role Skill',
                'verbose_name_plural': 'Role Skills',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('CS', 'Combat Skill'), ('MS', 'Movement Skill'), ('SS', 'Special Skill')], max_length=4)),
                ('attribute', models.CharField(choices=[('CHA', 'CHA'), ('CON', 'CON'), ('DEX', 'DEX'), ('INT', 'INT'), ('STR', 'STR'), ('WIL', 'WIL')], max_length=16)),
                ('untrained', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=16)),
                ('height', models.CharField(max_length=16)),
                ('CHA', models.IntegerField()),
                ('CON', models.IntegerField()),
                ('DEX', models.IntegerField()),
                ('INT', models.IntegerField()),
                ('STR', models.IntegerField()),
                ('WIL', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Species',
                'verbose_name_plural': 'Species',
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('power_level', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Spell',
                'verbose_name_plural': 'Spells',
            },
        ),
        migrations.CreateModel(
            name='SpellElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Spell Element',
                'verbose_name_plural': 'Spell Elements',
            },
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prerequisite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Talent')),
            ],
            options={
                'verbose_name': 'Talent',
                'verbose_name_plural': 'Talents',
            },
        ),
        migrations.CreateModel(
            name='TalentExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.CharField(choices=[('Cold Toughness', 'Cold Toughness'), ('Disease Resistance', 'Disease Resistance'), ('Electrical Toughness', 'Electrical Toughness'), ('Heat Toughness', 'Heat Toughness'), ('Initiative', 'Initiative'), ('Morale', 'Morale'), ('Physical Toughness', 'Physical Toughness'), ('Posion Resistance', 'Posion Resistance')], max_length=50)),
                ('mod', models.IntegerField()),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Talent')),
            ],
            options={
                'verbose_name': 'Talent Extra',
                'verbose_name_plural': 'Talent Extras',
            },
        ),
        migrations.CreateModel(
            name='TalentSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod', models.IntegerField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Skill')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Talent')),
            ],
            options={
                'verbose_name': 'Talent Skill',
                'verbose_name_plural': 'Talent Skills',
            },
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfarog.Item')),
                ('AV', models.IntegerField(default=0)),
                ('MS_mod', models.IntegerField(default=0)),
                ('stealth_mod', models.IntegerField(default=0)),
                ('swimming_mod', models.IntegerField(default=0)),
                ('damage', models.CharField(default=0, max_length=50)),
            ],
            options={
                'verbose_name': 'Armor',
                'verbose_name_plural': 'Armor',
            },
            bases=('myfarog.item',),
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfarog.Item')),
                ('capacity_weight', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Container',
                'verbose_name_plural': 'Containers',
            },
            bases=('myfarog.item',),
        ),
        migrations.CreateModel(
            name='Earring',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfarog.Item')),
            ],
            options={
                'verbose_name': 'Earring',
                'verbose_name_plural': 'Earrings',
            },
            bases=('myfarog.item',),
        ),
        migrations.CreateModel(
            name='Footwear',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfarog.Item')),
            ],
            options={
                'verbose_name': 'Footwear',
                'verbose_name_plural': 'Footwear',
            },
            bases=('myfarog.item',),
        ),
        migrations.CreateModel(
            name='Glove',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfarog.Item')),
            ],
            options={
                'verbose_name': 'Glove',
                'verbose_name_plural': 'Gloves',
            },
            bases=('myfarog.item',),
        ),
        migrations.CreateModel(
            name='Helmet',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfarog.Item')),
                ('AV', models.IntegerField(default=0)),
                ('perception_mod', models.IntegerField(default=0)),
                ('missile_mod', models.IntegerField(default=0)),
                ('shading_mod', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Helmet',
                'verbose_name_plural': 'Helmets',
            },
            bases=('myfarog.item',),
        ),
        migrations.CreateModel(
            name='Necklace',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfarog.Item')),
            ],
            options={
                'verbose_name': 'Necklace',
                'verbose_name_plural': 'Necklaces',
            },
            bases=('myfarog.item',),
        ),
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfarog.Item')),
            ],
            options={
                'verbose_name': 'Ring',
                'verbose_name_plural': 'Rings',
            },
            bases=('myfarog.item',),
        ),
        migrations.CreateModel(
            name='Shield',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfarog.Item')),
                ('ME', models.IntegerField(default=0)),
                ('MI', models.IntegerField(default=0)),
                ('MS_mod', models.IntegerField(default=0)),
                ('damage', models.CharField(default=0, max_length=50)),
                ('cut', models.IntegerField(default=0)),
                ('shock', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Shield',
                'verbose_name_plural': 'Shields',
            },
            bases=('myfarog.item',),
        ),
        migrations.CreateModel(
            name='Trinket',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfarog.Item')),
            ],
            options={
                'verbose_name': 'Trinket',
                'verbose_name_plural': 'Trinkets',
            },
            bases=('myfarog.item',),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfarog.Item')),
                ('damage', models.CharField(default=0, max_length=50)),
                ('weapon_type', models.CharField(choices=[('melee', 'Melee'), ('missile', 'Missile'), ('small Weapon', 'Small_weapon'), ('heavy Weapon', 'Heavy_weapon')], max_length=50)),
                ('cut', models.IntegerField(default=0)),
                ('shock', models.IntegerField(default=0)),
                ('range', models.IntegerField(default=0)),
                ('OV_mod', models.IntegerField(default=0)),
                ('DV_mod', models.IntegerField(default=0)),
                ('AP', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Weapon',
                'verbose_name_plural': 'Weapons',
            },
            bases=('myfarog.item',),
        ),
        migrations.AddField(
            model_name='spell',
            name='elements',
            field=models.ManyToManyField(blank=True, related_name='spell', related_query_name='spell', to='myfarog.SpellElement'),
        ),
        migrations.AddField(
            model_name='roleskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Skill'),
        ),
        migrations.AddField(
            model_name='role',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='roles', related_query_name='role', to='myfarog.RolePrerequisites'),
        ),
        migrations.AddField(
            model_name='itembonus',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.ItemBonusType'),
        ),
        migrations.AddField(
            model_name='item',
            name='bonuses',
            field=models.ManyToManyField(blank=True, related_name='items', related_query_name='items', to='myfarog.ItemBonus'),
        ),
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.ItemMaterial'),
        ),
        migrations.AddField(
            model_name='item',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='items', related_query_name='items', to='myfarog.ItemPrerequisites'),
        ),
        migrations.AddField(
            model_name='inventoryslot',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Item'),
        ),
        migrations.AddField(
            model_name='charactertalent',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Talent'),
        ),
        migrations.AddField(
            model_name='characterskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Skill'),
        ),
        migrations.AddField(
            model_name='characterinventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Item'),
        ),
        migrations.AddField(
            model_name='character',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Role'),
        ),
        migrations.AddField(
            model_name='character',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Species'),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Belt',
            fields=[
                ('container_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfarog.Container')),
            ],
            options={
                'verbose_name': 'Belt',
                'verbose_name_plural': 'Belts',
            },
            bases=('myfarog.container',),
        ),
        migrations.CreateModel(
            name='Jacket',
            fields=[
                ('container_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfarog.Container')),
            ],
            options={
                'verbose_name': 'Jacket',
                'verbose_name_plural': 'Jackets',
            },
            bases=('myfarog.container',),
        ),
        migrations.CreateModel(
            name='Pants',
            fields=[
                ('container_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfarog.Container')),
            ],
            options={
                'verbose_name': 'Pants',
                'verbose_name_plural': 'Pants',
            },
            bases=('myfarog.container',),
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('container_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfarog.Container')),
            ],
            options={
                'verbose_name': 'Shirt',
                'verbose_name_plural': 'Shirts',
            },
            bases=('myfarog.container',),
        ),
        migrations.AddField(
            model_name='character',
            name='armor_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Armor'),
        ),
        migrations.AddField(
            model_name='character',
            name='footwear_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Footwear'),
        ),
        migrations.AddField(
            model_name='character',
            name='helment_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Helmet'),
        ),
        migrations.AddField(
            model_name='character',
            name='left_earring_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='left_ear', to='myfarog.Earring'),
        ),
        migrations.AddField(
            model_name='character',
            name='left_glove_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='left_glove', to='myfarog.Glove'),
        ),
        migrations.AddField(
            model_name='character',
            name='left_hand_shield',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='left_hand', to='myfarog.Shield'),
        ),
        migrations.AddField(
            model_name='character',
            name='left_hand_weapon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='left_hand', to='myfarog.Weapon'),
        ),
        migrations.AddField(
            model_name='character',
            name='necklace_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Necklace'),
        ),
        migrations.AddField(
            model_name='character',
            name='right_earring_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='right_ear', to='myfarog.Earring'),
        ),
        migrations.AddField(
            model_name='character',
            name='right_glove_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='right_glove', to='myfarog.Glove'),
        ),
        migrations.AddField(
            model_name='character',
            name='right_hand_shield',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='right_hand', to='myfarog.Shield'),
        ),
        migrations.AddField(
            model_name='character',
            name='right_hand_weapon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='right_hand', to='myfarog.Weapon'),
        ),
        migrations.AddField(
            model_name='character',
            name='ring_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Ring'),
        ),
        migrations.AddField(
            model_name='character',
            name='trinket_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Trinket'),
        ),
    ]
