# Generated by Django 2.0.5 on 2018-06-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfarog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='capacity_dimensions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
