# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfarog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('height', models.CharField(max_length=16)),
                ('CHA', models.IntegerField()),
                ('CON', models.IntegerField()),
                ('DEX', models.IntegerField()),
                ('INT', models.IntegerField()),
                ('STR', models.IntegerField()),
                ('WIL', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='race',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myfarog.Role'),
            preserve_default=False,
        ),
    ]
