# Generated by Django 2.0.5 on 2018-06-03 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfarog', '0003_auto_20180603_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterinventory',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.InventorySlot'),
        ),
    ]
