# Generated by Django 2.0.5 on 2018-06-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfarog', '0004_characterinventory_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryslot',
            name='type',
            field=models.CharField(choices=[('shirt', 'Shirt'), ('pants', 'Pants'), ('jacket', 'Jacket'), ('footwear', 'Footwear'), ('belt', 'Belt'), ('backpack', 'Packpack'), ('left_sack', 'Left Sack'), ('right_sack', 'Right Sack')], default='backpack', max_length=100),
            preserve_default=False,
        ),
    ]
