# Generated by Django 2.0.5 on 2018-06-03 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfarog', '0005_inventoryslot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryslot',
            name='character',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_slot', to='myfarog.Character'),
            preserve_default=False,
        ),
    ]
