# Generated by Django 2.0.5 on 2018-06-04 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfarog', '0007_auto_20180603_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSpell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Character')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Spell')),
            ],
            options={
                'verbose_name': 'Character Spell',
                'verbose_name_plural': 'Character Spell',
            },
        ),
    ]
