# Generated by Django 2.0.5 on 2018-06-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfarog', '0009_auto_20180604_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterspell',
            name='character',
        ),
        migrations.RemoveField(
            model_name='characterspell',
            name='spell',
        ),
        migrations.AddField(
            model_name='character',
            name='spells',
            field=models.ManyToManyField(blank=True, related_name='spells', related_query_name='spells', to='myfarog.Spell'),
        ),
        migrations.DeleteModel(
            name='CharacterSpell',
        ),
    ]
