# Generated by Django 2.0.5 on 2018-06-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfarog', '0010_auto_20180604_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterinventory',
            name='character',
        ),
        migrations.RemoveField(
            model_name='characterinventory',
            name='item',
        ),
        migrations.RemoveField(
            model_name='characterinventory',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='inventoryslot',
            name='character',
        ),
        migrations.RemoveField(
            model_name='inventoryslot',
            name='item',
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('shirt', 'Shirt'), ('pants', 'Pants'), ('weapon', 'Weapon'), ('armor', 'Armor'), ('helmet', 'Helmet'), ('shield', 'Shield'), ('gloves', 'Gloves'), ('belt', 'Belt'), ('footwear', 'Footwear'), ('necklace', 'Necklace'), ('earring', 'Earring'), ('ring', 'Ring'), ('trinket', 'Trinket'), ('backpack', 'Backpack'), ('sack', 'Sack'), ('misc', 'Misc')], max_length=50),
        ),
        migrations.DeleteModel(
            name='CharacterInventory',
        ),
        migrations.DeleteModel(
            name='InventorySlot',
        ),
    ]
