# Generated by Django 2.0.5 on 2018-06-05 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfarog', '0011_auto_20180605_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterCompartmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Character')),
            ],
            options={
                'verbose_name': 'Character Compartment Item',
                'verbose_name_plural': 'Character Compartment Item',
            },
        ),
        migrations.CreateModel(
            name='Compartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('main', 'Main'), ('pocket', 'pocket')], max_length=100)),
                ('hidden', models.BooleanField(default=False)),
                ('lockable', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Compartment',
                'verbose_name_plural': 'compartments',
            },
        ),
        migrations.RemoveField(
            model_name='container',
            name='capacity_dimensions',
        ),
        migrations.RemoveField(
            model_name='container',
            name='capacity_weight',
        ),
        migrations.AddField(
            model_name='compartment',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='compartments', to='myfarog.Container'),
        ),
        migrations.AddField(
            model_name='charactercompartmentitem',
            name='compartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Compartment'),
        ),
        migrations.AddField(
            model_name='charactercompartmentitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfarog.Item'),
        ),
    ]
