# Generated by Django 2.0.5 on 2018-06-07 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfarog', '0012_auto_20180605_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BattleRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rounds', to='myfarog.Battle')),
            ],
            options={
                'verbose_name': 'Battle Round',
                'verbose_name_plural': 'Battle Rounds',
            },
        ),
        migrations.CreateModel(
            name='BattleRoundLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('attack', 'Attack'), ('cast', 'Cast'), ('use', 'Use')], max_length=100)),
                ('statement', models.CharField(max_length=500)),
                ('results', models.CharField(max_length=1000)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='actor_logs', to='myfarog.Character')),
                ('battle_round', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='myfarog.BattleRound')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='target_logs', to='myfarog.Character')),
            ],
            options={
                'verbose_name': 'Battle Round Log',
                'verbose_name_plural': 'Battle Round Logs',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('characters', models.ManyToManyField(blank=True, related_name='parties', related_query_name='parties', to='myfarog.Character')),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
            },
        ),
        migrations.AlterField(
            model_name='charactercompartmentitem',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='myfarog.Character'),
        ),
        migrations.AddField(
            model_name='battle',
            name='parties',
            field=models.ManyToManyField(blank=True, related_name='battles', related_query_name='battles', to='myfarog.Party'),
        ),
    ]
