# Generated by Django 2.0.5 on 2018-06-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfarog', '0013_auto_20180607_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='fright_mod',
            field=models.IntegerField(default=0),
        ),
    ]
