# Generated by Django 2.0.5 on 2018-06-07 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfarog', '0014_party_fright_mod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='fright_mod',
        ),
        migrations.AddField(
            model_name='party',
            name='frightener',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='party_frightener', to='myfarog.Character'),
            preserve_default=False,
        ),
    ]
