# Generated by Django 2.0.5 on 2018-06-07 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfarog', '0015_auto_20180607_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='frightener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='party_frightener', to='myfarog.Character'),
        ),
    ]
