# Generated by Django 2.0.5 on 2018-06-09 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfarog', '0016_auto_20180607_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleRoundAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Battle Round Action',
                'verbose_name_plural': 'Battle Round Actions',
            },
        ),
        migrations.AddField(
            model_name='battleround',
            name='step',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='stun_status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Stunned', 'Strunned'), ('Knocked Down', 'Knocked Down'), ('Knocked Out', 'Knocked Out')], default='Normal', max_length=16),
        ),
        migrations.AddField(
            model_name='battleroundaction',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='actor_actions', to='myfarog.Character'),
        ),
        migrations.AddField(
            model_name='battleroundaction',
            name='battle_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='actions', to='myfarog.BattleRound'),
        ),
        migrations.AddField(
            model_name='battleroundaction',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='target_actions', to='myfarog.Character'),
        ),
    ]
